config/routes.rb
HowTo::Application.routes.draw do
  root :to => "guides#index"

  resources :guides do
    resources :steps
  end

end

app/models/guide.rb
class Guide < ActiveRecord::Base
  attr_accessible :Description, :Topic
  has_many :steps, :dependent => :destroy
end

app/models/step.rb
class Step < ActiveRecord::Base
  attr_accessible :step, :guide_id
  belongs_to :guide
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  # GET /guides
  # GET /guides.json
  def index
    @guides = Guide.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @guides }
    end
  end

  # GET /guides/1
  # GET /guides/1.json
  def show
    @guide = Guide.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @guide }
    end
  end

  # GET /guides/new
  # GET /guides/new.json
  def new
    @guide = Guide.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @guide }
    end
  end

  # GET /guides/1/edit
  def edit
    @guide = Guide.find(params[:id])
  end

  # POST /guides
  # POST /guides.json
  def create
    @guide = Guide.new(params[:guide])

    respond_to do |format|
      if @guide.save
        format.html { redirect_to @guide, notice: 'Guide was successfully created.' }
        format.json { render json: @guide, status: :created, location: @guide }
      else
        format.html { render action: "new" }
        format.json { render json: @guide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /guides/1
  # PUT /guides/1.json
  def update
    @guide = Guide.find(params[:id])

    respond_to do |format|
      if @guide.update_attributes(params[:guide])
        format.html { redirect_to @guide, notice: 'Guide was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @guide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guides/1
  # DELETE /guides/1.json
  def destroy
    @guide = Guide.find(params[:id])
    @guide.destroy

    respond_to do |format|
      format.html { redirect_to guides_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController

  before_filter :load_guide
  # GET /steps
  # GET /steps.json
  def index
    @steps = @guide.steps.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @steps }
    end
  end

  # GET /steps/1
  # GET /steps/1.json
  def show
    @step = @guide.steps.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @step }
    end
  end

  # GET /steps/new
  # GET /steps/new.json
  def new
    @step = Step.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @step }
    end
  end

  # GET /steps/1/edit
  def edit
    @step = @guide.steps.find(params[:id])
  end

  # POST /steps
  # POST /steps.json
  def create
    @step = @guide.steps.new(params[:step])

    respond_to do |format|
      if @step.save
        #current_guide.posts << @step
        format.html { redirect_to [@guide, @step], notice: 'Step was successfully created.' }
        format.json { render json: @step, status: :created, location: @step }
      else
        format.html { render action: "new" }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /steps/1
  # PUT /steps/1.json
  def update
    @step = guide.steps.find(params[:id])

    respond_to do |format|
      if @step.update_attributes(params[:step])
        format.html { redirect_to [@guide, @step], notice: 'Step was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /steps/1
  # DELETE /steps/1.json
  def destroy
    @step = @guide.steps.find(params[:id])
    @step.destroy

    respond_to do |format|
      format.html { redirect_to guide_steps_path(@guide) }
      format.json { head :no_content }
    end
  end

private
  def load_guide
     @guide = Guide.find(params[:guide_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/guides/_form.html.erb
<%= form_for(@guide) do |f| %>
  <% if @guide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guide.errors.count, "error") %> prohibited this guide from being saved:</h2>

      <ul>
      <% @guide.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Topic %><br />
    <%= f.text_field :Topic %>
  </div>
  <div class="field">
    <%= f.label :Description %><br />
    <%= f.text_area :Description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guides/edit.html.erb
<h1>Editing guide</h1>

<%= render 'form' %>

<%= link_to 'Show', @guide %> |
<%= link_to 'Back', guides_path %>

app/views/guides/index.html.erb
<h1>Listing guides</h1>

<table>
  <tr>
    <th>Topic</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @guides.each do |guide| %>
  <tr>
    <td><%= link_to "#{guide.Topic}", guide %></td>
    <td><%= guide.Description %></td>
    <td><%= link_to 'Remove', guide, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Guide', new_guide_path %>

app/views/guides/new.html.erb
<h1>New guide</h1>

<%= render 'form' %>

<%= link_to 'Back', guides_path %>

app/views/guides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Topic:</b>
  <%= @guide.Topic %>
</p>

<p>
  <b>Description:</b>
  <%= @guide.Description %>
</p>
<table>
  <tr>
    <th>Step</th>
    <th></th>
    <th></th>
  </tr>

<% @guide.steps.each do |stp| %>
  <tr>
    <td><%= stp.step %></td>
    <td><%= link_to 'Edit', edit_guide_step_path(@guide, @step) %></td>
    <td><%= link_to 'Destroy', stp, method: :delete %></td>
  </tr>
<% end %>
</table>



<%= link_to 'Edit Topic', edit_guide_path(@guide) %> |
<%= link_to 'Back', guides_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HowTo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/steps/_form.html.erb
<%= form_for([@guide, @step]) do |f| %>
  <% if @step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@step.errors.count, "error") %> prohibited this step from being saved:</h2>

      <ul>
      <% @step.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :step %><br />
    <%= f.text_field :step %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/steps/edit.html.erb
<h1>Editing step</h1>

<%= render 'form' %>

<%= link_to 'Show', guide_steps_path(@guide, @step) %> |
<%= link_to 'Back', guide_steps_path(@guide) %>

app/views/steps/index.html.erb
<h1>Listing steps</h1>

<table>
  <tr>
    <th>Step</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @steps.each do |step| %>
  <tr>
    <td><%= step.step %></td>
    <td><%= link_to 'Show', step %></td>
    <td><%= link_to 'Edit', edit_step_path(step) %></td>
    <td><%= link_to 'Destroy', step, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Step', new_guide_step_path %>

app/views/steps/new.html.erb
<h1>New step</h1>

<%= render 'form' %>

<%= link_to 'Back', guide_steps_path(@guide) %>

app/views/steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Step:</b>
  <%= @step.step %>
</p>


<%= link_to 'Edit', edit_guide_step_path(@parent, @step) %> |
<%= link_to 'Back', guide_steps_path(@guide) %>